### ISSUE TITLE
Issue with restoring from history

### ISSUE THREAD

**Issue by meiichikaebara** [ReDEnergy/SessionSync#35] opened 2018-04-18 22:36 UTC
I've noticed that most of the time, restoring from history does not work properly. When there is only one window, restoring from history may open only a fraction of the tabs that were actually open in the window. When there are multiple windows, most of the time trying to restore them will only open multiple windows that all only have the new tab open.

A better example of the first problem is if I have a session with a single window with 4 tabs. Restoring this session from history opens up a window with only 2 of the tabs open, not the full 4.

A better example of the second problem is if I have a session with 4 windows, each with multiple tabs. Restoring this session from history will still open 4 windows, but every single window will only have the new tab open. None of the actual tabs will be restored.

**Comment by ReDEnergy** [comment] 2018-04-18 22:44
Hi. Thanks for reporting the issue.
Can you please tell me what operating system are you using because there are some API issues on Linux and I want to know if it's related to that or not.

By most of the time do you mean that sometimes it works as expected ? I will look into this because the behavior seems really strange and all I know is that I send the API commands to the browser and they should work.

**Comment by meiichikaebara** [comment] 2018-04-19 03:25
I am using Windows 10. I read about the issues with the Linux API, but I am not sure if it's connected in this case.

**Comment by ReDEnergy** [comment] 2018-04-19 12:29
Ok. So I can confirm a definitely strange bug when the session contains multiple windows. Sometimes seems to open some of the tabs randomly into other windows. Anyway, clearly there's a bug here and I will try to fix it as soon as possible. 
Sorry for not testing it properly before launch (not sure how I missed this... (most probably because I don't use the feature that much and also because I usually save all my sessions as bookmarks beforehand)
Thanks a lot for submitting the issue here and not going right to the reviews page leave a bad rating. 
I will try to have a fix as soon as possible.

**Comment by meiichikaebara** [comment] 2018-04-19 17:27
No problem my dude. I am excited to see what the new update for this extension brings, since it's finally moved me to go back to Firefox after they switched to the Quantum update and broke legacy extensions like Session Manager.

**Comment by meiichikaebara** [comment] 2018-04-23 02:53
I checked it out and it works exactly as expected! Thanks for the prompt response.

**Comment by ReDEnergy** [comment] 2018-04-23 02:55
Awesome. Thanks a lot.

**Comment by ReDEnergy** [comment] 2018-04-23 16:31
There's an issue with the version number and Firefox will update and overwrite the version you installed manually. I updated the version number to fix this to [Version 3.0.1](https://www.dropbox.com/s/n5stbwi2zh9vm1a/session_sync-3.0.1beta.xpi?dl=0).
Later today after a few more test I will launch an official version and that will be updated automatically.

**Comment by ReDEnergy** [comment] 2018-04-26 22:48
Fixed in version 3.0.1 - 544850e
Release available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/session-sync/)

**Closed by ReDEnergy** 2018-04-26 22:48 UTC
Labels: bug
